version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
    - 7.23.0
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.13.8
  - dependency-name: "@lwc/babel-plugin-component"
    versions:
    - 1.17.5
  - dependency-name: html-webpack-plugin
    versions:
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: lwc
    versions:
    - 1.17.5
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.13.8
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.24.2
  - dependency-name: workbox-webpack-plugin
    versions:
    - 6.1.0
  - dependency-name: yeoman-generator
    versions:
    - 4.13.0
  - dependency-name: rollup
    versions:
    - 2.38.3
- package-ecosystem: npm
  directory: "/packages/create-lwc-app"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/lwc-services"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@salesforce/eslint-config-lwc"
    versions:
    - 0.10.0
    - 0.11.0
    - 0.11.1
  - dependency-name: "@lwc/eslint-plugin-lwc"
    versions:
    - 0.12.0
    - 0.12.1
    - 0.12.2
    - 1.0.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@lwc/jest-transformer"
    versions:
    - 9.0.0
  - dependency-name: "@lwc/jest-serializer"
    versions:
    - 9.0.0
  - dependency-name: "@lwc/jest-resolver"
    versions:
    - 9.0.0
  - dependency-name: "@lwc/jest-preset"
    versions:
    - 9.0.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0
    - 5.3.0
    - 5.3.1
  - dependency-name: "@types/webpack-merge"
    versions:
    - 5.0.0
