---
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.2.0
        steps:
            - checkout
            - restore_cache: &restore_cache
                  keys:
                      - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - run:
                  name: Install dependencies
                  command: yarn install
            - run:
                  name: Prettier verification
                  command: yarn prettier:verify
            - run:
                  name: ESlint verification
                  command: yarn lint
            - run:
                  name: Test TypeScript compilation lwc-create-app
                  command: cd ./packages/lwc-create-app
                      tsc -b
            - run:
                  name: Test TypeScript compilation lwc-services
                  command: cd ./packages/lwc-services
                      tsc -b
            # - run:
            #       name: Testing
            #       command: yarn test:unit
            # - run:
            #       name: Submitting code coverage to codecov
            #       command: |
            #           ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
            #           curl -s https://codecov.io/bash | bash

        cache:
            steps:
                - checkout
                - run:
                      name: Install dependencies
                      command: yarn
                - save_cache:
                      key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
                      paths:
                          - ~/cli/node_modules
                          - /usr/local/share/.cache/yarn
                          - /usr/local/share/.config/yarn

workflows:
    version: 2
    commit-workflow:
        jobs:
            - build
