---
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.2.0
        steps:
            - checkout
            - restore_cache: &restore_cache
                  keys:
                      - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "./packages/lwc-create-app/yarn.lock"}}
                      - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "./packages/lwc-services/yarn.lock"}}
                      - v1-npm-{{checksum ".circleci/config.yml"}}
            - run:
                  name: Install dependencies
                  command: yarn install
            - run: ./packages/lwc-create-app/bin/run --version
            - run: ./packages/lwc-services/bin/run --version
            - run:
                  name: Prettier verification
                  commany: yarn prettier:verify
            - run:
                  name: ESlint verification
                  commany: yarn lint
            # - run:
            #       name: Testing
            #       command: yarn test:unit
            # - run:
            #       name: Submitting code coverage to codecov
            #       command: |
            #           ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
            #           curl -s https://codecov.io/bash | bash

        cache:
            steps:
                - checkout
                - run:
                      name: Install dependencies
                      command: yarn
                - save_cache:
                      key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
                      paths:
                          - ~/cli/node_modules
                          - /usr/local/share/.cache/yarn
                          - /usr/local/share/.config/yarn

workflows:
    version: 2
    'lwc-create-app':
        jobs:
            - node-latest
            - node-8
            - node-10
            - cache:
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
