name: Autoresponse Issue

on:
    issues:
        types: [opened]

jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - uses: rytswd/respost@v0.1.0
              with:
                  title: ${{ secrets.AUTORESPONSE_TITLE }}
                  body: ${{ secrets.AUTORESPONSE_BODY_ISSUE }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
