# Unique name for this workflow
name: create-lwc-app build

# Definition when the workflow should run
on:
    push:
        branches:
            - main

# Jobs to be executed
jobs:
    formatting-and-linting:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            # Cache node_modules to speed up the process
            - name: 'Restore node_modules cache'
              id: cache-yarn
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      yarn-${{ env.cache-name }}-
                      yarn-

            # Install npm dependencies for Prettier and Jest
            - name: 'Install npm dependencies'
              if: steps.cache-yarn.outputs.cache-hit != 'true'
              run: yarn install

            # Prettier formatting
            - name: 'Code formatting verification with Prettier'
              run: yarn prettier:verify

            # ESlint
            - name: 'ESlint verification'
              run: yarn lint

            # Build
            - name: 'Build'
              run: yarn build
